"""
Tests for history and reports endpoints

Requirements: 12.3, 12.5
"""
import pytest
from pathlib import Path
import tempfile
import shutil
from fastapi.testclient import TestClient

# Import the app
import sys
sys.path.insert(0, str(Path(__file__).parent.parent))

from main import app, Config
from memory_store import MemoryStore
import time


@pytest.fixture
def client():
    """Create test client"""
    return TestClient(app)


@pytest.fixture
def temp_reports_dir():
    """Create temporary reports directory"""
    temp_dir = tempfile.mkdtemp()
    yield temp_dir
    shutil.rmtree(temp_dir)


def test_history_endpoint_empty(client):
    """Test history endpoint with no data"""
    response = client.get("/api/research/history")
    
    # Should return 200 even with no data
    assert response.status_code in [200, 503]  # 503 if memory store not initialized
    
    if response.status_code == 200:
        data = response.json()
        assert "total" in data
        assert "queries" in data
        assert isinstance(data["queries"], list)


def test_history_endpoint_with_pagination(client):
    """Test history endpoint with pagination parameters"""
    response = client.get("/api/research/history?limit=10&offset=0&min_relevance=0.5")
    
    # Should return 200 or 503
    assert response.status_code in [200, 503]
    
    if response.status_code == 200:
        data = response.json()
        assert "total" in data
        assert "limit" in data
        assert "offset" in data
        assert "queries" in data
        assert data["limit"] == 10
        assert data["offset"] == 0


def test_history_endpoint_invalid_params(client):
    """Test history endpoint with invalid parameters"""
    # Negative limit should still work (FastAPI will handle validation)
    response = client.get("/api/research/history?limit=-1")
    
    # Should either work or return validation error
    assert response.status_code in [200, 422, 503]


def test_reports_list_endpoint_empty(client):
    """Test reports list endpoint with no reports"""
    response = client.get("/api/reports")
    
    assert response.status_code == 200
    data = response.json()
    assert "total" in data
    assert "reports" in data
    assert isinstance(data["reports"], list)


def test_reports_list_endpoint_with_limit(client):
    """Test reports list endpoint with limit parameter"""
    response = client.get("/api/reports?limit=5")
    
    assert response.status_code == 200
    data = response.json()
    assert "total" in data
    assert "reports" in data
    assert len(data["reports"]) <= 5


def test_get_report_not_found(client):
    """Test getting a non-existent report"""
    response = client.get("/api/reports/report_2099-01-01_00-00-00")
    
    assert response.status_code == 404
    data = response.json()
    assert "detail" in data


def test_get_report_invalid_id(client):
    """Test getting a report with invalid ID format"""
    response = client.get("/api/reports/invalid_id")
    
    assert response.status_code == 400
    data = response.json()
    assert "detail" in data
    assert "Invalid report ID format" in data["detail"]


def test_reports_list_with_existing_reports(client, temp_reports_dir):
    """Test reports list with actual report files"""
    # Create a mock report file
    report_content = """# Research Report: Test Query

**Generated:** 2025-11-22 10:00:00  
**Report ID:** report_2025-11-22_10-00-00  
**Query ID:** test-query-id  
**Confidence Score:** 0.85  
**Processing Time:** 1000ms

---

## Executive Summary

This is a test report.

## Key Findings

- Finding 1
- Finding 2

## Detailed Analysis

Test analysis content.

## Sources

Test sources.

## Confidence Assessment

**Overall Confidence:** 0.85

## Key Insights & Patterns

Test insights.

## Related Research

No similar past research found.

## Metadata

### Query Information

- **Intent Type:** test
- **Key Topics:** test

---

*Generated by Adaptive Research Agent*
"""
    
    # Write report file
    report_path = Path(temp_reports_dir) / "research_report_2025-11-22_10-00-00.md"
    report_path.write_text(report_content, encoding='utf-8')
    
    # Temporarily override Config.REPORT_OUTPUT_DIR
    original_dir = Config.REPORT_OUTPUT_DIR
    Config.REPORT_OUTPUT_DIR = temp_reports_dir
    
    try:
        response = client.get("/api/reports")
        
        assert response.status_code == 200
        data = response.json()
        assert data["total"] >= 1
        assert len(data["reports"]) >= 1
        
        # Check report metadata
        report = data["reports"][0]
        assert "report_id" in report
        assert "filename" in report
        assert "query" in report
        assert "timestamp" in report
        assert "file_size_bytes" in report
        assert "confidence_score" in report
        
    finally:
        # Restore original directory
        Config.REPORT_OUTPUT_DIR = original_dir


def test_get_specific_report(client, temp_reports_dir):
    """Test getting a specific report by ID"""
    # Create a mock report file
    report_content = """# Research Report: Specific Test Query

**Generated:** 2025-11-22 11:00:00  
**Report ID:** report_2025-11-22_11-00-00  
**Query ID:** specific-test-query-id  
**Confidence Score:** 0.92  
**Processing Time:** 1500ms

---

## Executive Summary

This is a specific test report.

## Key Findings

- Specific Finding 1
- Specific Finding 2

---

*Generated by Adaptive Research Agent*
"""
    
    # Write report file
    report_path = Path(temp_reports_dir) / "research_report_2025-11-22_11-00-00.md"
    report_path.write_text(report_content, encoding='utf-8')
    
    # Temporarily override Config.REPORT_OUTPUT_DIR
    original_dir = Config.REPORT_OUTPUT_DIR
    Config.REPORT_OUTPUT_DIR = temp_reports_dir
    
    try:
        response = client.get("/api/reports/report_2025-11-22_11-00-00")
        
        assert response.status_code == 200
        data = response.json()
        
        # Check response structure
        assert "report_id" in data
        assert "filename" in data
        assert "content" in data
        assert "metadata" in data
        
        # Check content
        assert data["report_id"] == "report_2025-11-22_11-00-00"
        assert data["filename"] == "research_report_2025-11-22_11-00-00.md"
        assert "Specific Test Query" in data["content"]
        
        # Check metadata
        metadata = data["metadata"]
        assert metadata["report_id"] == "report_2025-11-22_11-00-00"
        assert "Specific Test Query" in metadata["query"]
        assert metadata["confidence_score"] == 0.92
        
    finally:
        # Restore original directory
        Config.REPORT_OUTPUT_DIR = original_dir


def test_history_response_structure(client):
    """Test that history response has correct structure"""
    response = client.get("/api/research/history")
    
    if response.status_code == 200:
        data = response.json()
        
        # Check top-level fields
        assert "total" in data
        assert "limit" in data
        assert "offset" in data
        assert "queries" in data
        
        # Check queries structure if any exist
        if data["queries"]:
            query = data["queries"][0]
            assert "query_id" in query
            assert "query" in query
            assert "timestamp" in query
            assert "relevance_score" in query
            assert "confidence_score" in query
            assert "sources_count" in query


def test_reports_response_structure(client):
    """Test that reports list response has correct structure"""
    response = client.get("/api/reports")
    
    assert response.status_code == 200
    data = response.json()
    
    # Check top-level fields
    assert "total" in data
    assert "reports" in data
    
    # Check reports structure if any exist
    if data["reports"]:
        report = data["reports"][0]
        assert "report_id" in report
        assert "filename" in report
        assert "query" in report
        assert "timestamp" in report
        assert "file_size_bytes" in report
        assert "confidence_score" in report


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
