#!/usr/bin/env node

import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";
import * as fs from "fs";
import * as path from "path";

// Report configuration
const REPORT_OUTPUT_DIR = process.env.REPORT_OUTPUT_DIR || "./reports";

// Ensure reports directory exists
if (!fs.existsSync(REPORT_OUTPUT_DIR)) {
  fs.mkdirSync(REPORT_OUTPUT_DIR, { recursive: true });
}

// Create MCP server
const server = new Server(
  {
    name: "research-tools-mcp-server",
    version: "1.0.0",
  },
  {
    capabilities: {
      tools: {},
    },
  }
);

// Define tools
server.setRequestHandler(ListToolsRequestSchema, async () => {
  return {
    tools: [
      {
        name: "generate_report",
        description: "Generate a markdown research report",
        inputSchema: {
          type: "object",
          properties: {
            query: {
              type: "string",
              description: "The research query",
            },
            answer: {
              type: "string",
              description: "The synthesized answer",
            },
            sources: {
              type: "array",
              description: "List of API sources used",
              items: {
                type: "object",
              },
            },
            metadata: {
              type: "object",
              description: "Additional metadata (query_id, processing_time, etc.)",
            },
          },
          required: ["query", "answer", "sources"],
        },
      },
    ],
  };
});

// Handle tool calls
server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;

  try {
    switch (name) {
      case "generate_report":
        return await handleGenerateReport(args);
      default:
        throw new Error(`Unknown tool: ${name}`);
    }
  } catch (error: any) {
    console.error(`[Research Tools MCP] Error executing tool ${name}:`, error.message);
    return {
      content: [
        {
          type: "text",
          text: `Error: ${error.message}`,
        },
      ],
      isError: true,
    };
  }
});

// Implementation: generate_report
async function handleGenerateReport(args: any) {
  const { query, answer, sources, metadata = {} } = args;

  console.log(`[Research Tools MCP] Generating report for query: ${query}`);

  try {
    // Generate timestamp for filename
    const timestamp = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
    const filename = `research_report_${timestamp}.md`;
    const filepath = path.join(REPORT_OUTPUT_DIR, filename);

    // Build markdown report
    const report = buildMarkdownReport(query, answer, sources, metadata);

    // Write report to file
    fs.writeFileSync(filepath, report, "utf8");

    console.log(`[Research Tools MCP] Report generated: ${filepath}`);

    return {
      content: [
        {
          type: "text",
          text: JSON.stringify({
            success: true,
            report_path: filepath,
            filename: filename,
            message: "Report generated successfully",
          }),
        },
      ],
    };
  } catch (error: any) {
    throw new Error(`Failed to generate report: ${error.message}`);
  }
}

// Build markdown report content
function buildMarkdownReport(
  query: string,
  answer: string,
  sources: any[],
  metadata: any
): string {
  const now = new Date().toISOString().replace("T", " ").slice(0, 19);
  
  let report = `# Research Report: ${query}\n\n`;
  report += `**Generated:** ${now}\n`;
  
  if (metadata.query_id) {
    report += `**Query ID:** ${metadata.query_id}\n`;
  }
  
  if (metadata.processing_time_ms) {
    report += `**Processing Time:** ${metadata.processing_time_ms}ms\n`;
  }
  
  report += `\n---\n\n`;
  report += `## Answer\n\n${answer}\n\n`;
  report += `---\n\n`;
  report += `## Sources\n\n`;
  
  if (sources && sources.length > 0) {
    sources.forEach((source, index) => {
      report += `${index + 1}. **${source.api_name || "Unknown API"}**\n`;
      if (source.api_id) {
        report += `   - API ID: ${source.api_id}\n`;
      }
      if (source.endpoint) {
        report += `   - Endpoint: ${source.endpoint}\n`;
      }
      if (source.verified !== undefined) {
        report += `   - Verified: ${source.verified ? "Yes" : "No"}\n`;
      }
      report += `\n`;
    });
  } else {
    report += "No sources available.\n\n";
  }
  
  report += `---\n\n`;
  report += `*Generated by Adaptive Research Agent*\n`;
  
  return report;
}

// Start the server
async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error("[Research Tools MCP] Server started successfully");
}

main().catch((error) => {
  console.error("[Research Tools MCP] Fatal error:", error);
  process.exit(1);
});
